export const GET_USERS = 'GET_USERS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SHOW_SUCCESS_TOAST = 'SHOW_SUCCESS_TOAST';
export const RESET_AUTHENTICATION_STATE = 'RESET_AUTHENTICATION_STATE'
